In [18]:
import numpy as np
import pandas
import scipy
import matplotlib
import seaborn
import sklearn

In [6]:
print("fr")

fr


In [5]:
import csv
with open("week1.csv",'rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['hello', ' my', ' name', ' is', ' tom', ' marvolo', ' riddle']
['yeh ', 'jo ', 'machal ', 'machalke ', 'gaaa', ' raha ', 'hai', ' sang', ' nayi ', 'si ', 'dhun']


In [9]:
reader=csv.DictReader(open('week1.csv','rt'))
for row in reader:
    print(row['hello'])

yeh 
teri


In [15]:
with open('week1.csv','a') as file:
    writer=csv.writer(file,delimiter=',',quotechar=" ",quoting=csv.QUOTE_MINIMAL)
    writer.writerow(('tum','se','hi','din','hota','hai'))

In [23]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
b = a.reshape(3,3)
print(b)

(1, 9)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
arr= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
n=arr.size
for i in range(n):
    if i%2 !=0:
     arr[i]=-1

print(arr)     

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [38]:
import numpy as np

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
n = x.size

arr1 = []
arr2 = []

for i in range(n):
    if x[i] > y[i]:
        arr1.append(i)
    elif x[i]==y[i]:
        arr2.append(i)

arr1 = np.array(arr1)
arr2 = np.array(arr2)

print(arr1)
print(arr2)


[1 2 4 5 6 7 8 9]
[0]


In [43]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [42]:
arr4= np.arange(100).reshape(5,-1)
print(arr4)
arr4[:,:4]


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])